# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField(default='0')),
                ('lng', models.FloatField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=50)),
                ('is_transporting', models.IntegerField(choices=[(1, 'Active'), (0, 'Disabled')], default=0)),
                ('battery_life', models.PositiveSmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='DropPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('is_available', models.IntegerField(choices=[(1, 'Active'), (0, 'Disabled')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('radius', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dropPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.DropPoint')),
                ('logistic_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.LogisticCenter')),
            ],
        ),
        migrations.CreateModel(
            name='StyleURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('href', models.URLField()),
                ('scale', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (0, 'Disabled')], default=0)),
                ('drone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dlp.Drone')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.Package')),
            ],
        ),
        migrations.AddField(
            model_name='logisticcenter',
            name='style_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.StyleURL'),
        ),
        migrations.AddField(
            model_name='droppoint',
            name='logistic_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.LogisticCenter'),
        ),
        migrations.AddField(
            model_name='droppoint',
            name='style_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.StyleURL'),
        ),
        migrations.AddField(
            model_name='drone',
            name='logistic_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.LogisticCenter'),
        ),
        migrations.AddField(
            model_name='drone',
            name='style_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.StyleURL'),
        ),
    ]
