# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0003_logisticcenter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='logistic_center',
        ),
        migrations.AlterField(
            model_name='logisticcenter',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_centers', to='dlp.City'),
        ),
    ]
