# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0005_auto_20160610_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='logistic_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drones', to='dlp.LogisticCenter'),
        ),
        migrations.AlterField(
            model_name='droppoint',
            name='logistic_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoints', to='dlp.LogisticCenter'),
        ),
        migrations.AlterField(
            model_name='package',
            name='dropPoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='dlp.DropPoint'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='drone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='dlp.Drone'),
        ),
    ]
