# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0006_auto_20160611_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droppoint',
            name='logistic_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droppoints', to='dlp.LogisticCenter'),
        ),
    ]
