# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0007_auto_20160611_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.IntegerField(choices=[(2, 'Pending'), (1, 'Sending'), (0, 'Sent')], default=2),
        ),
    ]
