# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0008_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Disabled')], default=1),
        ),
    ]
