# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0009_auto_20160621_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styleurl',
            name='href',
        ),
        migrations.AddField(
            model_name='styleurl',
            name='earth_url',
            field=models.CharField(default='something', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='styleurl',
            name='maps_url',
            field=models.CharField(default='static/images/galaxy_icons/droppoints/1.png', max_length=50),
            preserve_default=False,
        ),
    ]
