# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0010_auto_20160628_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
