# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0012_auto_20160629_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='style_url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dlp.StyleURL'),
            preserve_default=False,
        ),
    ]
