# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0014_auto_20160704_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
