# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0015_auto_20160704_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='logistic_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistic_center', to='dlp.Package'),
            preserve_default=False,
        ),
    ]
