# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0017_auto_20160704_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='place_id',
            field=models.CharField(default='ChIJf9M750jgphIRr6pZ0qIu06A', max_length=100),
            preserve_default=False,
        ),
    ]
