# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0018_city_place_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='dropPoint',
            new_name='drop_point',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='is_transporting',
        ),
        migrations.RemoveField(
            model_name='droppoint',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='is_active',
        ),
        migrations.AddField(
            model_name='drone',
            name='status',
            field=models.IntegerField(choices=[(1, 'Delivering'), (0, 'Waiting')], default=0),
        ),
        migrations.AddField(
            model_name='transport',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Finished')], default=1),
        ),
    ]
