# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0019_auto_20160712_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='lng',
            field=models.FloatField(),
        ),
    ]
