#!/bin/bash

if [ -z $1 ]; then
    ip = "0.0.0.0:8000"
else
    ip=$1
fi
galaxy_ip=$2
echo "runserver will run on $ip"
xterm -e "python manage.py runserver $ip" & t1=$!
xterm -e "redis-server" & t2=$!
xterm -e "python manage.py celeryd" & t3=$!
xterm -e "python manage.py celeryd" & t4=$!
xterm -e "python manage.py celerybeat" & t5=$!
echo "#!/bin/bash
pgrep -P $t1 | xargs kill
pgrep -P $t5 | xargs kill
pgrep -P $t3 | xargs kill
pgrep -P $t4 | xargs kill
pgrep -P $t2 | xargs kill
sshpass -p 'lqgalaxy' ssh lg@$galaxy_ip \"echo '' > /var/www/html/kmls.txt\"
sshpass -p 'lqgalaxy' ssh lg@$galaxy_ip \"echo '' > /var/www/html/kmls_4.txt\"
" > exitdlp
echo "To exit run: bash exitdlp"
exit